import { db, categoriesTable, productsTable } from "@workspace/db";
import { eq } from "drizzle-orm";

async function run() {
  console.log("Starting trendy product insertion...");

  // 1. Ensure categories exist
  const categories = [
    { name: "T-Shirts", slug: "t-shirts", description: "Custom printed t-shirts for all occasions" },
    { name: "Hoodies", slug: "hoodies", description: "Premium quality hoodies with custom designs" },
    { name: "Mugs", slug: "mugs", description: "Personalized mugs perfect for gifts" },
    { name: "Caps", slug: "caps", description: "Stylish caps with custom embroidery" },
    { name: "Long Sleeves", slug: "long-sleeves", description: "Premium long sleeve shirts with custom designs" },
    { name: "Water Bottles", slug: "water-bottles", description: "Durable aluminum water bottles with custom prints" },
    { name: "Custom Orders", slug: "custom-orders", description: "Special custom orders tailored to your needs" },
  ];

  const catMap: Record<string, number> = {};
  for (const cat of categories) {
    let existing = await db.select().from(categoriesTable).where(eq(categoriesTable.slug, cat.slug));
    if (existing.length === 0) {
      const [inserted] = await db.insert(categoriesTable).values(cat).returning();
      catMap[cat.slug] = inserted.id;
      console.log(`Created category: ${cat.name}`);
    } else {
      catMap[cat.slug] = existing[0].id;
    }
  }

  // 2. Define trendy products
  const products = [
    // T-Shirts
    {
      name: "Birthday Celebration Tee",
      slug: "birthday-celebration-tee",
      description: "Celebrate in style with our vibrant 'Happy Birthday' typography T-shirt. Made from 100% premium cotton, it's the perfect gift for your special day.",
      price: "699",
      discountPrice: "599",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_birthday.png",
      featured: true,
      customizable: true,
      tags: ["birthday", "celebration", "gift"],
    },
    {
      name: "Apology Kitten Tee",
      slug: "apology-kitten-tee",
      description: "Say 'I'm Sorry' with this adorable sad kitten illustration. A soft and comfortable way to mend any relationship.",
      price: "699",
      discountPrice: "599",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_sorry.png",
      featured: false,
      customizable: true,
      tags: ["sorry", "cute", "gift"],
    },
    {
      name: "Keep Going Motivational Tee",
      slug: "keep-going-motivational-tee",
      description: "Stay inspired with our minimalist 'Keep Going' T-shirt. Elegant white typography on a premium navy blue base.",
      price: "699",
      discountPrice: "599",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_motivational.png",
      featured: true,
      customizable: true,
      tags: ["motivational", "minimalist", "inspiration"],
    },
    {
      name: "Viral Meme Culture Tee",
      slug: "viral-meme-culture-tee",
      description: "Wear the internet's favorite moments. This trendy T-shirt features a viral meme illustration that's sure to start conversations.",
      price: "750",
      discountPrice: "649",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_meme.png",
      featured: true,
      customizable: true,
      tags: ["meme", "trendy", "viral"],
    },
    {
      name: "Minimalist Face Line Art Tee",
      slug: "minimalist-face-line-art-tee",
      description: "A touch of modern art for your wardrobe. Features a continuous line drawing of a human face for a sophisticated, artistic look.",
      price: "750",
      discountPrice: "649",
      categoryId: catMap["t-shirts"],
      imageUrl: "/assets/products/tshirt_lineart.png",
      featured: false,
      customizable: true,
      tags: ["art", "minimalist", "lineart"],
    },
    // Hoodies
    {
      name: "Urban Explorer Streetwear Hoodie",
      slug: "urban-explorer-streetwear-hoodie",
      description: "Dominate the streets with our 'Urban Explorer' graffiti-style hoodie. Premium fleece for maximum warmth and style.",
      price: "1599",
      discountPrice: "1399",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_streetwear.png",
      featured: true,
      customizable: true,
      tags: ["streetwear", "graffiti", "urban"],
    },
    {
      name: "Cozy Winter Wishes Hoodie",
      slug: "cozy-winter-wishes-hoodie",
      description: "Stay warm this winter with our 'Winter Wishes' snowflake design. Soft fleece and a cozy fit for those chilly nights.",
      price: "1599",
      discountPrice: "1399",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_winter.png",
      featured: true,
      customizable: true,
      tags: ["winter", "cozy", "snowflake"],
    },
    {
      name: "Pro Gamer Neon Hoodie",
      slug: "pro-gamer-neon-hoodie",
      description: "Level up your style with our 'Pro Gamer' neon controller design. Perfect for long gaming sessions and late-night streams.",
      price: "1699",
      discountPrice: "1499",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_gaming.png",
      featured: true,
      customizable: true,
      tags: ["gaming", "neon", "pro"],
    },
    {
      name: "Aesthetic Anime Girl Hoodie",
      slug: "aesthetic-anime-girl-hoodie",
      description: "A minimalist anime-inspired design for the modern fan. Clean lines and a sleek aesthetic on a premium white hoodie.",
      price: "1699",
      discountPrice: "1499",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_anime.png",
      featured: false,
      customizable: true,
      tags: ["anime", "aesthetic", "minimalist"],
    },
    {
      name: "Stay Wild Nature Hoodie",
      slug: "stay-wild-nature-hoodie",
      description: "Connect with the outdoors. Our 'Stay Wild' hoodie features nature-inspired typography on a deep forest green base.",
      price: "1599",
      discountPrice: "1399",
      categoryId: catMap["hoodies"],
      imageUrl: "/assets/products/hoodie_quote.png",
      featured: false,
      customizable: true,
      tags: ["nature", "wild", "adventure"],
    },
    // Mugs
    {
      name: "Confetti Birthday Mug",
      slug: "confetti-birthday-mug",
      description: "Start their birthday morning with a splash of color! This premium ceramic mug features a vibrant 'Happy Birthday' confetti design.",
      price: "499",
      discountPrice: "399",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_birthday.png",
      featured: true,
      customizable: true,
      tags: ["birthday", "mug", "gift"],
    },
    {
      name: "World's Best Boss Humor Mug",
      slug: "worlds-best-boss-humor-mug",
      description: "The classic office staple. Whether it's for your boss or a Michael Scott fan, this 'World's Best Boss' mug is a winner.",
      price: "449",
      discountPrice: "349",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_boss.png",
      featured: false,
      customizable: true,
      tags: ["boss", "humor", "office"],
    },
    {
      name: "Love You to the Moon Mug",
      slug: "love-you-to-the-moon-mug",
      description: "A romantic keepsake featuring a beautiful crescent moon and stars. Perfect for anniversaries or just to say 'I love you'.",
      price: "499",
      discountPrice: "399",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_love.png",
      featured: true,
      customizable: true,
      tags: ["love", "romantic", "anniversary"],
    },
    {
      name: "Best Cat Mom Paw Mug",
      slug: "best-cat-mom-paw-mug",
      description: "For the feline-obsessed! This cute mug features a 'Best Cat Mom' illustration with a charming cat paw.",
      price: "449",
      discountPrice: "349",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_cat.png",
      featured: false,
      customizable: true,
      tags: ["cat", "pet", "gift"],
    },
    {
      name: "First Coffee Then Life Mug",
      slug: "first-coffee-then-life-mug",
      description: "The ultimate mug for coffee lovers. Modern typography that speaks the truth about your morning routine.",
      price: "449",
      discountPrice: "349",
      categoryId: catMap["mugs"],
      imageUrl: "/assets/products/mug_coffee.png",
      featured: true,
      customizable: true,
      tags: ["coffee", "typographic", "morning"],
    },
    // Water Bottles
    {
      name: "Hydrate or Die Fitness Bottle",
      slug: "hydrate-or-die-fitness-bottle",
      description: "Stay motivated at the gym with our 'Hydrate or Die' matte black aluminum bottle. Durable and stylish.",
      price: "899",
      discountPrice: "749",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_fitness.png",
      featured: true,
      customizable: true,
      tags: ["fitness", "gym", "hydrate"],
    },
    {
      name: "Save the Ocean Eco Bottle",
      slug: "save-the-ocean-eco-bottle",
      description: "Make a statement for the planet. This teal aluminum bottle features a beautiful 'Save the Ocean' wave and turtle design.",
      price: "899",
      discountPrice: "749",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_eco.png",
      featured: true,
      customizable: true,
      tags: ["eco", "ocean", "sustainable"],
    },
    {
      name: "Personalized Script Name Bottle",
      slug: "personalized-script-name-bottle",
      description: "Your bottle, your name. Elegant rose gold aluminum with a custom script font for a truly personal touch.",
      price: "999",
      discountPrice: "849",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_name.png",
      featured: true,
      customizable: true,
      tags: ["personalized", "gift", "elegant"],
    },
    {
      name: "Hydration Tracker Time Marker Bottle",
      slug: "hydration-tracker-time-marker-bottle",
      description: "Never forget to drink water again. Features time markers to help you reach your daily hydration goals.",
      price: "899",
      discountPrice: "749",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_tracker.png",
      featured: false,
      customizable: true,
      tags: ["hydration", "health", "tracker"],
    },
    {
      name: "Explore More Adventure Bottle",
      slug: "explore-more-adventure-bottle",
      description: "The perfect companion for your next hike. Forest green aluminum with a classic 'Explore More' compass design.",
      price: "899",
      discountPrice: "749",
      categoryId: catMap["water-bottles"],
      imageUrl: "/assets/products/bottle_adventure.png",
      featured: false,
      customizable: true,
      tags: ["adventure", "outdoor", "travel"],
    },
    // Caps
    {
      name: "All Star Sports Cap",
      slug: "all-star-sports-cap",
      description: "A classic navy blue cap with bold 'All Star' white embroidery. Perfect for game day or casual wear.",
      price: "799",
      discountPrice: "699",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_sports.png",
      featured: true,
      customizable: true,
      tags: ["sports", "classic", "cap"],
    },
    {
      name: "Urban Vibes Street Snapback",
      slug: "urban-vibes-street-snapback",
      description: "Vibrant graffiti-style design on a premium black snapback. Add some urban edge to your outfit.",
      price: "899",
      discountPrice: "799",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_street.png",
      featured: true,
      customizable: true,
      tags: ["streetwear", "snapback", "urban"],
    },
    {
      name: "Minimalist Geometric Logo Cap",
      slug: "minimalist-geometric-logo-cap",
      description: "Clean, simple, and sophisticated. Features a small geometric logo embroidered on a grey base.",
      price: "799",
      discountPrice: "699",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_logo.png",
      featured: false,
      customizable: true,
      tags: ["minimalist", "logo", "cap"],
    },
    {
      name: "Bad Hair Day Dad Hat",
      slug: "bad-hair-day-dad-hat",
      description: "The perfect solution for those messy hair mornings. Stylish pink dad hat with modern typography.",
      price: "749",
      discountPrice: "649",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_hairday.png",
      featured: true,
      customizable: true,
      tags: ["casual", "dad-hat", "funny"],
    },
    {
      name: "Wanderlust Travel Cap",
      slug: "wanderlust-travel-cap",
      description: "For the world travelers. Beige baseball cap with a 'Wanderlust' mountain and sun illustration.",
      price: "799",
      discountPrice: "699",
      categoryId: catMap["caps"],
      imageUrl: "/assets/products/cap_travel.png",
      featured: false,
      customizable: true,
      tags: ["travel", "wanderlust", "adventure"],
    },
    // Long Sleeves
    {
      name: "Focus Minimalist Long Sleeve",
      slug: "focus-minimalist-long-sleeve",
      description: "Stay focused with our clean typography design on a premium white long sleeve shirt.",
      price: "899",
      discountPrice: "799",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_corporate.png",
      featured: true,
      customizable: true,
      tags: ["minimalist", "corporate", "clean"],
    },
    {
      name: "Vaporwave Retro Long Sleeve",
      slug: "vaporwave-retro-long-sleeve",
      description: "Bring back the 90s with our neon vaporwave design on a sleek black long sleeve shirt.",
      price: "999",
      discountPrice: "899",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_retro.png",
      featured: true,
      customizable: true,
      tags: ["retro", "90s", "vaporwave"],
    },
    {
      name: "Wanderlust Nature Long Sleeve",
      slug: "wanderlust-nature-long-sleeve",
      description: "For the nature lovers. Features a beautiful forest and mountain line art design on forest green.",
      price: "999",
      discountPrice: "899",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_nature.png",
      featured: true,
      customizable: true,
      tags: ["nature", "travel", "adventure"],
    },
    {
      name: "Abstract Paint Flow Long Sleeve",
      slug: "abstract-paint-flow-long-sleeve",
      description: "A wearable piece of art. Fluid watercolor strokes on a premium white long sleeve base.",
      price: "999",
      discountPrice: "899",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_artistic.png",
      featured: false,
      customizable: true,
      tags: ["art", "abstract", "creative"],
    },
    {
      name: "Creativity Modern Font Long Sleeve",
      slug: "creativity-modern-font-long-sleeve",
      description: "Celebrate your creative side with this elegant modern font design on a grey base.",
      price: "899",
      discountPrice: "799",
      categoryId: catMap["long-sleeves"],
      imageUrl: "/assets/products/longsleeve_typographic.png",
      featured: false,
      customizable: true,
      tags: ["creative", "typographic", "modern"],
    },
  ];

  for (const product of products) {
    const existing = await db.select().from(productsTable).where(eq(productsTable.slug, product.slug));
    if (existing.length === 0) {
      await db.insert(productsTable).values({
        ...product,
        images: [product.imageUrl],
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Black", "Navy", "Grey"],
        stock: 100,
        rating: "4.9",
        reviewCount: Math.floor(Math.random() * 50) + 10,
        updatedAt: new Date(),
      } as any);
      console.log(`Inserted product: ${product.name}`);
    }
  }

  console.log("Trendy product insertion complete!");
  process.exit(0);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
